#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Print how closely each translated zone reproduces the MATLAB original.

Reads the reference generated by dump_matlab_reference.m. Run from the repo root:
    python tools/report_zone_accuracy.py
"""
import csv, math, os, sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from frp_flexure import zones                                    # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "matlab_reference.csv")
PAR = os.path.join(HERE, "matlab_params.csv")

ARG_ORDER = ["L", "b", "h", "alpha", "E", "epcr", "beta_1", "beta_2", "beta_3",
             "eta_1", "eta_2", "eta_3", "xi", "omega", "eta_c", "n", "kappa",
             "eta_s", "rho_c", "rho_t", "iota", "psi", "rho_x"]

params = {}
with open(PAR, newline="") as fh:
    for row in csv.DictReader(fh):
        params[int(row["set"])] = {k: float(v) for k, v in row.items() if k != "set"}

rows = []
with open(REF, newline="") as fh:
    for r in csv.DictReader(fh):
        rows.append((r["zone"], int(r["set"]), float(r["beta"]),
                     float(r["k"]), float(r["M"])))

order = []
for z, *_ in rows:
    if z not in order:
        order.append(z)

print(f'{"zone":<10}{"states":>8}{"worst rel dk":>16}{"worst rel dM":>16}')
print("-" * 50)
gk = gM = 0.0
for z in order:
    by_set = {}
    for name, s, beta, k_ref, M_ref in rows:
        if name == z:
            by_set.setdefault(s, []).append((beta, k_ref, M_ref))
    wk = wM = 0.0
    n = 0
    for s, rs in by_set.items():
        betas = [x[0] for x in rs]
        p = params[s]
        args = [p[a] for a in ARG_ORDER]
        fn = getattr(zones, z)
        kk, MM = (fn(betas, *args) if z == "zone111" else fn(p["M_cr"], betas, *args))
        for j, (beta, k_ref, M_ref) in enumerate(rs):
            if not (math.isfinite(k_ref) and math.isfinite(M_ref)):
                continue
            n += 1
            wk = max(wk, abs(float(kk[j]) - k_ref) / max(abs(k_ref), 1e-12))
            wM = max(wM, abs(float(MM[j]) - M_ref) / max(abs(M_ref), 1e-12))
    gk, gM = max(gk, wk), max(gM, wM)
    print(f"{z:<10}{n:>8}{wk:>16.2e}{wM:>16.2e}")

print("-" * 50)
print(f'{"all":<10}{"":>8}{gk:>16.2e}{gM:>16.2e}')
